# Generated by Django 3.2 on 2023-08-03 21:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('n_processed', models.IntegerField(null=True)),
                ('n_inserted', models.IntegerField(null=True)),
                ('n_deleted', models.IntegerField(null=True)),
                ('n_updated', models.IntegerField(null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('params', models.CharField(max_length=255, null=True)),
                ('load', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'log de processo de carga',
                'verbose_name_plural': 'log de processos de cargas',
                'db_table': 'elt_load_log',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('vendedor', models.TextField()),
                ('equipe_vendas', models.TextField()),
                ('foto', models.URLField()),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.loadlog')),
            ],
            options={
                'verbose_name': 'Cadastro de Vendedores',
                'verbose_name_plural': 'Cadastro de Vendedores',
                'db_table': 'elt_vendedor',
                'unique_together': {('codigo', 'equipe_vendas')},
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('nfe', models.IntegerField()),
                ('codigo_produto', models.TextField()),
                ('codigo_vendedor', models.TextField()),
                ('equipe_vendas', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.loadlog')),
            ],
            options={
                'verbose_name': 'Histórico de vendas',
                'verbose_name_plural': 'Histórico de vendas',
                'db_table': 'elt_venda',
                'unique_together': {('data', 'nfe', 'codigo_produto')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('grupo', models.TextField()),
                ('linha', models.TextField()),
                ('fornecedor', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.loadlog')),
            ],
            options={
                'verbose_name': 'Cadastro de Produto',
                'verbose_name_plural': 'Cadastro de Produtos',
                'db_table': 'elt_produto',
                'unique_together': {('codigo', 'grupo', 'linha', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.TextField()),
                ('ano', models.IntegerField()),
                ('vendedor', models.TextField()),
                ('faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('margem_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('notas_emitidas', models.IntegerField()),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.loadlog')),
            ],
            options={
                'verbose_name': 'Cadastro de Metas',
                'verbose_name_plural': 'Cadastro de Metass',
                'db_table': 'elt_meta',
                'unique_together': {('mes', 'ano', 'vendedor')},
            },
        ),
    ]
