# Generated by Django 3.2 on 2023-08-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadlog',
            old_name='start_at',
            new_name='started_at',
        ),
    ]
