# Generated by Django 3.2 on 2023-12-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_rename_start_at_loadlog_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('feriado', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(max_length=10)),
                ('dia_util', models.BooleanField(db_index=True, default=False)),
                ('ponto_facultativo', models.BooleanField(db_index=True, default=False)),
                ('ano', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('dia', models.IntegerField(null=True)),
                ('mes_ano', models.CharField(max_length=50)),
                ('trimestre', models.CharField(max_length=2)),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.loadlog')),
            ],
            options={
                'verbose_name': 'Cadadario',
                'db_table': 'elt_calendar',
            },
        ),
    ]
