# Generated by Django 3.2 on 2023-12-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='feriado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
